source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in inspec-digitalocean.gemspec
gemspec

group :development do
  gem 'rake'
  gem 'rubocop'
  gem 'github_changelog_generator'
end
